name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Install PostgreSQL client
      run: |
        sudo apt-get -yqq install libpq-dev
        sudo apt install postgresql

    - name: Start PostgreSQL
      run: |
        sudo systemctl start postgresql
        sudo systemctl enable postgresql

    - name: Create database and schema
      run: |
        sudo -u postgres psql -c "CREATE USER postgres WITH PASSWORD 'postgres';""
        sudo -u postgres psql -c 'GRANT ALL PRIVILEGES ON DATABASE postgres TO postgres;'

    - name: Run the default task with postgresl
      env:
        DATABASE_ADAPTER: postgresql
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
        RAILS_ENV: test
      run: bundle exec rake

    - name: Run the default task with sqlite3
      env:
        DATABASE_ADAPTER: sqlite3
        RAILS_ENV: test
      run: bundle exec rake
